### PR TITLE
beginning and end characters of address text should be visible

### PR DESCRIPTION
**Pull request by tantommy**
## Description

- address feedback from https://liftedinit.slack.com/archives/C02EFTD4HQ9/p1662069162703239
- shortens the address text so that the first and last characters are visible

## Related Issue

Fixes https://github.com/liftedinit/albert/issues/80

## Testing

- adds jest tests

## Screenshots (if applicable)

Before:
image

After:
image

### CODE REVIEW

**Comment by tantommy** [comment]
merge https://github.com/liftedinit/albert/pull/72 first

**Comment by fmorency** [comment]
Thanks for this @tantommy. 

Not sure if relevant but here are some screenshots of dialogs that don't appear fixed.

- the "Send" dialog



- the "add account" dialog


 
- after account creation



I didn't test the transaction history

**Comment by hansl** [comment]
@fmorency can you specify which OS and Browser (including exact versions) you're using?

**Comment by fmorency** [comment]
> @fmorency can you specify which OS and Browser (including exact versions) you're using?

Linux Manjaro 22.0.0, Kernel 5.10.136
Firefox 104.0.2

**Comment by tantommy** [comment]
> Thanks for this @tantommy.
> 
> Not sure if relevant but here are some screenshots of dialogs that don't appear fixed.
> 
> * the "Send" dialog
> 
> 
> 
> * the "add account" dialog
> 
> 
> 
> * after account creation
> 
> 
> 
> I didn't test the transaction history

these should be acceptable as they are actual Input elements and can be clicked on to view the full address.

this PR fixes any of the address that are display only.  For example, when creating a transaction (sending tokens) and the confirmation screen appears.  The address here is cutoff and cannot be clicked on to view the full address.  In these cases, we will shorten the address so that the beginning and end characters are shown.

**Review by fmorency — APPROVED** [review]
Didn't check the code, only the feature.

**Pull request merged**
